### PR TITLE
New QA Handbook page

### PR DESCRIPTION
**Pull request by cwarnermm**
Added new QA Handbook page for Rainforest processes.

### CODE REVIEW

**Comment by cwarnermm** [comment]
@lindy65 - This draft Handbook update, featuring Rainforest process steps, is ready for your review.

Can you update the following pieces of this PR, please?
- Add an ALT tag `[alt_text]` for each image link that's picked up by screen reading technologies. Or, remove the ALT tag property altogether if preferred. If removing, please remove `[alt_text]` from each coded image link. It's a good practice to include ALT tags, but I'll leave that choice up to you.
- Add an image tooltip `"image_tooltip"` for each image link that's visible when someone hovers over the image. OR, remove the image tooltip property altogether if preferred. If removing, please remove only `"image_tooltip"` from each coded image link. Image tooltips are often perceived as a nice to have, and I'll leave this choice up to you.
- Review the editorial updates I made to numbering conventions throughout each section. I took some liberties with numbering and sub-numbering for an easier Markdown code experience. This means that some sections won't be numbered exactly the same as they are in the Google doc draft. Let me know if there's any numbering that needs an adjustment and I'm happy to help.
- Please let me know if I've changed any other aspect of this content in a way you didn't intend, or if any of my editorial edits has diverted from what you intended initially.

Please also note that I struggled to indent screenshots for sub-steps like a., b., c., and so on. If indentation here is important to have, I'm happy to take another crack at it.

**Comment by cwarnermm** [comment]
@lindy65 - Previews aren't generated for updates made to this repository. However, you can still see what your changes are going to look like by displaying a rich diff view of the contents from the **Files changed** tab of this PR:
Screen Shot 2022-03-24 at 2 44 29 PM

**Review by justinegeffen — DISMISSED** [review]

**Review by lindy65 — DISMISSED** [review]
Looks good to me @cwarnermm!  Thank you so much for your kind assistance with this PR - very much appreciated!

**Comment by cwarnermm** [comment]
@justinegeffen - Would you be open to help add this new QA page into the Handbook LHS please?

**Review by justinegeffen — DISMISSED** [review]

**Review by justinegeffen — APPROVED** [review]

**Pull request merged**
