### PR TITLE
Update company-agreements.md

### PR DESCRIPTION
**Pull request by justinegeffen**
Removed $ from amounts in line with rest of docs. Minor punctuation fixes.

### CODE REVIEW

**Comment by TQuock** [comment]
Approved. As these are grammar and formatting changes VP of Finance and Operations and the CEO do not need to approve

**Review by TQuock — APPROVED** [review]
Looks good

**Comment by TQuock** [comment]
@justinegeffen I think we also need to update the root as the ToC is structured as follows: operations/company-operations/company-processes/company-agreements.md

Right now it's operations/operations/company-agreements.md

**Comment by justinegeffen** [comment]
I see what you mean - I'm not sure we can rename the second "operations" to "company operations" (even though it is more accurate) as it's the name of the folder and may (would?) invalidate all the content in that folder. 

@jasonblais, looping you in for comment.

**Comment by jasonblais** [comment]
@TQuock @justinegeffen we can keep it as is. GitBook automatically builds the URL based on its location in the TOC and the name of the file
image

**Pull request merged**
