### PR TITLE
Update web-properties.md

### PR DESCRIPTION
**Pull request by justinegeffen**
Updated content and quality owners.

### CODE REVIEW

**Comment by justinegeffen** [comment]
I noticed this area may be out of date based on https://github.com/mattermost/mattermost-handbook/pull/281. LMK if anything else is amiss. 

Aside: This does need to be updated at some stage but that's a discussion for another PR.

**Review by jasonblais — CHANGES_REQUESTED** [review]
Let's pick one owner for each. I'm happy to be the temporary content owner if you can help with quality control (with AmyB is backup?)

**Comment by rbradleyhaas** [comment]
@jasonblais do we want to put Hanna or Ian or leave it blank as the owner for mattermost.com?

**Comment by jasonblais** [comment]
@rbradleyhaas Good question. Let's make Hanna (https://github.com/hannaparks) as the owner of content and Asaad (https://github.com/asaadmahmood) as the owner of quality control for now. cc @justinegeffen

**Review by rbradleyhaas — DISMISSED** [review]

**Review by jasonblais — APPROVED** [review]

**Pull request merged**
