### PR TITLE
Create Accounting.MD

### PR DESCRIPTION
**Pull request by natalie-hub**
Create Accounting page

### CODE REVIEW

**Review by TQuock — DISMISSED** [review]

**Comment by justinegeffen** [comment]
Thanks, @natalie-hub! Where will this live in the navigation (SUMMARY.md)?

**Review by justinegeffen — APPROVED** [review]

**Comment by TQuock** [comment]
@justinegeffen I'll create a separate pull request to update the Summary page for this. It will live under Operations/Finance

**Review by TQuock — APPROVED** [review]

**Comment by justinegeffen** [comment]
@TQuock, is this page still needed?

**Comment by TQuock** [comment]
@justinegeffen - this is not needed at this time. Thanks for checking

**Pull request closed without merging**
