### PR TITLE
Create_Spending_Company_Money.md

### PR DESCRIPTION
**Pull request by TQuock**
Creating new page

### CODE REVIEW

**Comment by natalie-hub** [comment]
LGTM

**Review by natalie-hub — DISMISSED** [review]
LGTM

**Comment by justinegeffen** [comment]
@TQuock, is this going to be separate to: https://handbook.mattermost.com/company/how-to-guides-for-staff/how-to-spend-company-money or do you want to duplicate that page in another section of the Handbook?

**Comment by TQuock** [comment]
@justinegeffen - looking to eventually move the How to Spend pages down to Finance. Making a big overhaul in the current structure of where content is sitting. This is the start of it to streamline the intake and make it easier for users to find information on our handbook

**Comment by justinegeffen** [comment]
Awesome, @TQuock, that sounds great. One thing that @jasonblais noted is that the pages aren't hardcoded so moving things around in the TOC can lead to broken links. Jason has provided me with some options to consider. Do you have a timeline for your reorganization?

**Comment by TQuock** [comment]
@justinegeffen I am looking at over the next month to make the updates to the handbook and TOC. This is mostly going to be in piecemeal. My actions are as followed:

1. Create the outline for the TOC that is more aligned with how a user would navigate the handbook for Finance related items
2. Upload content to the these branches
3. Transfer existing pages under the new TOC outline

As the pages are not hardcoded, what is the recommended process to effectively move these pages?

**Comment by justinegeffen** [comment]
That sounds awesome, @TQuock, thank you. A reorganization would be really great. :) 

In terms of circumventing the TOC issue, I haven't had a chance to think it through. Can I get back to you on that next week? In the interim you can create a branch with all your changes or whatever works best for you.

**Comment by TQuock** [comment]
Thanks @justinegeffen! Next week works great. That should give me enough time to make all the branches and get a structured outline in place

**Comment by TQuock** [comment]
@justinegeffen is there anything holding this up for being provisioned at this time?

**Comment by justinegeffen** [comment]
Sorry, @TQuock! I've been on PTO hence the delay. :D LGTM.

**Review by justinegeffen — APPROVED** [review]

**Comment by TQuock** [comment]
@justinegeffen no worries at all. I didn't know you were on PTO. Sorry to bother you

**Comment by TQuock** [comment]
Hi @justinegeffen, I am not seeing this committed to the handbook if though you merged. I also did a cache reset

**Comment by justinegeffen** [comment]
There isn't an entry for this in the SUMMARY.md file, which is why it's not listed in the TOC. Would you be open to creating a new PR with the edit to SUMMARY.md where you'd like this page to be? That should resolve the issue.

**Comment by TQuock** [comment]
ahh yes, I will do that. Thanks for the reminder.

**Comment by justinegeffen** [comment]
Thanks, @TQuock!

**Pull request merged**
