### PR TITLE
Use the spreadsheet to track the R&D org as the single source of truth

### PR DESCRIPTION
**Pull request by jwilander**
#### Summary
The manual list included here was constantly out of date. The spreadsheet is where all R&D leads make changes and is the source of truth for org structure and membership. My proposal here is to replace the handbook list with a simple link to the spreadsheet.

### CODE REVIEW

**Review by wiersgallak — APPROVED** [review]

**Review by DSchalla — APPROVED** [review]

**Review by jasonblais — COMMENTED** [review]
Supportive of having a single source of truth.

For the spreadsheet, is there an opportunity to not restrict access to only those with mattermost.com email? E.g. during hiring process, I've sometimes got questions about R&D structure, who they'd be working with, etc, this page has been a helpful reference.

**Comment by jwilander** [comment]
I don't think there's any reason it can't be public. Let me confirm with a few people and if we're all good I'll make it public.

**Comment by justinegeffen** [comment]
This is a great idea, thank you!

**Review by justinegeffen — APPROVED** [review]

**Review by jasonblais — APPROVED** [review]
Saw the conversation in the R&D Leads channel, seems like there's lots involved to make the spreadsheet public.

It's a loss to not have access to this publicly (both in terms of usefulness for potential hires & in following our values), but don't want to block this PR given the implications of making the information public.

**Pull request merged**
