### PR TITLE
Update Workplace/People

### PR DESCRIPTION
**Pull request by cecilysullivan**
Updated People Team Contact Info and questions section

### CODE REVIEW

**Review by lynn915 — CHANGES_REQUESTED** [review]
Cecily, can you please update: 
1. My title to "Manager, People"? My title isn't "Manager, HR".
2. I think "Workplace Program Questions" should be in Ask the People Team channel but Vidhi and Hanna are the go-to's. also people@mattermost.com. Also people@mattermost.com
3. Same as above. I think general compensation analytics and Total Rewards Q's should also be in Ask the People Team channel but Praveen and Idayat are the people to ask.

**Review by cecilysullivan — COMMENTED** [review]
I made changes per Lynn's feedback.  Please review.  Thanks!

**Comment by lynn915** [comment]
Thanks, Cecily! LGTM

**Review by lynn915 — APPROVED** [review]
Thanks, Cecily! LGTM

**Review by justinegeffen — APPROVED** [review]

**Pull request merged**
