### PR TITLE
Proposed process for storing recorded calls in Salesforce

### PR DESCRIPTION
**Pull request by jasonblais**
Worked with Emily Hollinger on the proposed process.

@wiersgallak / @lfbrock I opened a PR so you can share feedback on the proposed process if any. If no concerns, I can roll it out when I'm back from PTO. We may set up the integration from SFDC call logs to Mattermost channel before rolling it out, so we don't lose visibility over new recorded calls that we have now in the Customer Feedback channel.

Feel free to share with other PMs for feedback as well.

### CODE REVIEW

**Comment by lfbrock** [comment]
@jasonblais - a couple questions: 

1. Are we just linking to the call recordings from within Salesforce, but they are stored elsewhere? (I'd like to make sure they are accessible so people who don't have Salesforce access can still listen to them if needed, for example eng/design for calls related to features they are working on) 

2. +1 on setting up the automation to Mattermost, I think it's really important that as much as possible people across the company can be close to the customer and sharing call notes is a good way to do that

**Review by wiersgallak — COMMENTED** [review]
The process looks fairly straight - forward to me.  Although I agree with Lindsay, that calls should be accessible to those who do not have access to SFDC. 

Wonder if we can outline the process for a customer not wanting to have the call recorded. Would we want detailed written notes added to Salesforce and the automation to post back to MM?

**Comment by jasonblais** [comment]
@lfbrock @wiersgallak Thanks for the feedback, will make some updates to the process and test how the integrations would work from SFDC --> ProductBoard and SFDC --> Mattermost.

There were also some suggestions in V2MOM measures sheet that I'll take into account, including from BizOps.

Specifically on:

> 1. Are we just linking to the call recordings from within Salesforce, but they are stored elsewhere? (I'd like to make sure they are accessible so people who don't have Salesforce access can still listen to them if needed, for example eng/design for calls related to features they are working on)

Correct, the intent is to link to them in Salesforce, like we have thus far done in Mattermost. That way access levels won't change.

> Wonder if we can outline the process for a customer not wanting to have the call recorded. Would we want detailed written notes added to Salesforce and the automation to post back to MM?

Good suggestion, will incorporate that in the process.

**Comment by jasonblais** [comment]
Discussed with Katie/Lindsay: we'll keep the calls in Mattermost for now given it's a lightweight process and allows us to easily share and track calls in one place.

One consideration is whether we want to begin storing calls in a single GDrive to make searching easier in future.

**Pull request closed without merging**
