### PR TITLE
Updated self-serve areas of ownership

### PR DESCRIPTION
**Pull request by johndavidlugtu**
Proposing to update areas of ownership of the self-serve team to better reflect stated priorities

### CODE REVIEW

**Comment by justinegeffen** [comment]
Thank you, @johndavidlugtu! Please let me know once you've signed the CLA so I can merge this helpful update. :)

**Comment by johndavidlugtu** [comment]
@justinegeffen thanks! I believe I've already signed it

**Comment by justinegeffen** [comment]
@johndavidlugtu, thank you! Will you be reopening a new PR for this? Or is this change not applicable anymore?

**Comment by johndavidlugtu** [comment]
Hi @justinegeffen sorry, I'm new to Github - I was meaning to accept the changes (proper casing) you've proposed.

**Comment by johndavidlugtu** [comment]
Reopening PR

**Review by justinegeffen — APPROVED** [review]

**Comment by justinegeffen** [comment]
Thank you, @johndavidlugtu! :)

**Pull request merged**
