### PR TITLE
Update internal-transfers.md

### PR DESCRIPTION
**Pull request by justinegeffen**
Minor formatting fixes and space removal.

### CODE REVIEW

**Comment by justinegeffen** [comment]
Ping on this, @natalie-hub :)

**Comment by jasonblais** [comment]
@justinegeffen quick thought - if the change is for minor fixes and space removals, wondering if we need an SME review, or if an editor review would suffice?

**Comment by justinegeffen** [comment]
Great point, @jasonblais. I've assigned another reviewer. :)

**Review by cwarnermm — APPROVED** [review]
Great update!

**Pull request merged**
