### PR TITLE
Update .gitbook.yaml

### PR DESCRIPTION
**Pull request by justinegeffen**
Investigating why some of the redirects aren't working.

@TQuock: In https://github.com/mattermost/mattermost-handbook/tree/0.2.1/operations/finance, we have a folder for "spending company money" and a file called "spending company money". I'm wondering if that's causing problems with the redirects. 

I can confirm that https://handbook.mattermost.com/operations/finance/spending-company-money/procurement/request-a-divvy-virtual-credit-card works from the LHS nav and I figured out that there's another link to that page which is what's broken. I've updated the redirect list to accommodate that. I *think* it's from when the page may have been moved previously although I can't be sure.

Let me know if there's any reorganization you want to do as part of this PR.

### CODE REVIEW

**Comment by justinegeffen** [comment]
@TQuock, just to add, I think this would be a good PR to fix up duplicates such as the "spending company money" folder/file as well as the Procurement section of Spending Company Money which is duplicated by Finance > Procurement. 

Happy to make all the changes if you can give me a breakdown of what you want. :)

**Comment by justinegeffen** [comment]
@TQuock, following up on this. Let me know if you need any help or want to sync up on this!

**Comment by TQuock** [comment]
@justinegeffen - can we talk through this. I am not quite certain what I need to do here as I see the right page in the LSB

**Comment by justinegeffen** [comment]
@TQuock, following up on this, I think it's good to merge as this is just the redirect file and shouldn't change anything in the navigation. It will ensure that no 404s are shown though.

**Review by TQuock — APPROVED** [review]
thanks @justinegeffen. Approved

**Pull request merged**
