### PR TITLE
Add gifting policy to handbook

### PR DESCRIPTION
**Pull request by jasonblais**
This is a summary of our gifting policy, providing guidance to our team members on what actions to take if they are offered a gift in exchange of sharing feedback on a tool we use, or may consider using in the future.

### CODE REVIEW

**Comment by it33** [comment]
@jasonblais I'm supportive of gifting policy, especially when it's for things like think alouds, usability tests, feedback, etc. That said, CEO shouldn't be on approval loops for changes to day-to-day expense policy, we should figure out from @TQuock who the right approval AORs should be within the finance org for PRs like these.

**Comment by jasonblais** [comment]
@it33 Apologies Ian, didn't intend to request a review from you, I had intended to request a review from Isabel as the SME.

It looks like there is automation in place with you as the "code owner" - and looks like you've been added as a reviewer to several PRs because of it. I don't have context on this change, but I'll touch base with Justine to help resolve when she's back on Monday

GitHub automated review request:
image

**Comment by it33** [comment]
Thanks Jason!

**Comment by TQuock** [comment]
Thanks, Jason for pulling this together. Really appreciate the proactiveness. I do agree with IJT that the AORs fall to Finance. More specifically, Isabel and Elad

- Isabel to propose the policy to be reviewed by the Finance team
- Elad to review against budget

We want to encourage the right motion while staying within the tax laws of each country. There is going to be some work Isabel and team will need to do. In the meantime, let's not slow down the process for you to get what you need. @ialorro are you ok with the proposal while we work through the larger Gift Giving and Receiving policy?

**Comment by it33** [comment]
Thanks all, @TQuock I have a couple of emails on timer for Monday around this, please ignore those when they pop up (I'm away from desktop email to change those timers right now). 

>The gift could be monetary (e.g. a $50 gift card), or a physical item (e.g. AirPod Pros).

Though now I'm on this thread, a few thoughts: 

1. Perhaps avoid referring to gifts as "monetary" (implying liquid payment) but as something like "merchant credit" or something.

After this PR is in, a couple of things to think about: 

1. There's specific policies prohibiting gifts to public employees in the U.S. and @TQuock maybe we should find that out from Erin F. and incorporate that, 
2. Not urgently, but at some point we should have a refresh on policy and training around FCPA (https://www.trade.gov/us-foreign-corrupt-practices-act#:~:text=Under%20the%20Foreign%20Corrupt%20Practices,of%20obtaining%20or%20retaining%20business.), which is perhaps more around sales and partners than gift cards and AirPods. When we bring in the FTE legal leader this would be one of their projects, ahead of that maybe finance can take a look in the context of compliance and figure out if we should have a sentence or two--maybe ask Alan B. I think there is (or was) wording around this in our partner agreements and commission plans, we might bolster it with something in our handbook and in future sales trainings. Again, more for legal leader to own in future, for now something for finance to consider.

**Comment by ialorro** [comment]
Hi everyone! 

Tim, yes, I am good with the proposal. In the meantime, I'll work through putting together our principles, policies and best practices etc. (as discussed) around this topic.

Jason, in the meantime, please reach out if you need additional guidance.

**Comment by jasonblais** [comment]
Thanks everyone! I've adjusted "monetary" to "merchant credits" per feedback above.

Sounds like we are otherwise good with merging the PR, with adjustments to principles, policies and best practices to come with further iterations, per above.

**Comment by justinegeffen** [comment]
> @it33 Apologies Ian, didn't intend to request a review from you, I had intended to request a review from Isabel as the SME.
> 
> It looks like there is automation in place with you as the "code owner" - and looks like you've been added as a reviewer to several PRs because of it. I don't have context on this change, but I'll touch base with Justine to help resolve when she's back on Monday
> 
> GitHub automated review request: image

Thanks @jasonblais! To clarify the code owner auto reviewer, this was requested with regard to changes to finance-related pages but was applied (by me) across the directory rather than individual pages. Thanks for raising this, I'll review the code owner configuration granularity to ensure no one is inundated with review requests. :)

**Comment by jasonblais** [comment]
Thank you Justine!

**Pull request merged**
