### PR TITLE
New product team hangouts

### PR DESCRIPTION
**Pull request by jasonblais**
In recent months, we haven't had sessions that brings the entire product org together (PM, UX, analytics, community, tech writing). Instead of just adding another meeting, I was thinking we could have weekly “Product Team Hangouts” that is less formal and helps build back more cohesion / relationship building opportunities into our org.

Devs run it off of Discord with audio-only - the reason being that it feels less formal and something people can jump on if they have free time.

I’m thinking we could try something similar - which is Zoom calls but audio-only, after the weekly R&D meeting.

@andrewbrown00 @wiersgallak Looking to hear your thoughts?

### CODE REVIEW

**Review by wiersgallak — APPROVED** [review]
Love this idea and the timing is great.  Thanks for putting together.

**Comment by jasonblais** [comment]
Heard it received positive reception in the weekly PM sync. Opening it up for editor review prior to merging.

cc @coreyhulen as FYI

**Review by justinegeffen — APPROVED** [review]
This is awesome, I'm super-pumped! :)

**Comment by andrewbrown00** [comment]
Thanks, @jasonblais, this is a great idea! What are your thoughts on trying [Claudio's voice plugin](https://github.com/streamer45/mattermost-plugin-talk)? If not, Zoom works 🙂

**Comment by jasonblais** [comment]
@andrewbrown00 I'm open to trying it out! There may be some steps needed to get it on community, but maybe a good opportunity to get that done :)

**Pull request merged**
