### PR TITLE
Update incident-response.md

### PR DESCRIPTION
**Pull request by justinegeffen**
Minor punctuation.

### CODE REVIEW

**Comment by justinegeffen** [comment]
@itao, wondering if this should be marked as 1% draft so we have an opportunity to iterate on it?

**Comment by itao** [comment]
@justinegeffen Thanks for reminding me of this. I think we should actually delete this since we now have a real product coming out that will be documented properly.

**Comment by justinegeffen** [comment]
Thanks, @itao! I'll remove it from the TOC.

@jasonblais, do we have a deprecation policy in place for handbook content? Or is removing it from the TOC sufficient?

**Comment by jasonblais** [comment]
@justinegeffen No deprecation policy. But in the event that someone lands on the page, let's add a redirect so they don't end up on a broken page? 

(Similar to the redirect at https://docs.mattermost.com/developer/localization.html)

**Comment by justinegeffen** [comment]
@jasonblais, I was thinking of removing it from the TOC but I think that ends up giving a 404 even if the page is still in the repo. So I propose keeping the page up, removing the current content, and adding a link to the updated/current docs. 

@itao, in terms of documentation, would you want to link to the admin docs or some other collateral?

**Comment by jasonblais** [comment]
@justinegeffen Proposal sounds great. :+1: We can also remove it from the TOC, it won't give a 404.

**Comment by itao** [comment]
@justinegeffen admin docs would be great, thanks!

Ian Tao
Product Manager, Mattermost, Inc.
ian.tao@mattermost.com | +1 (650) 667-8512 | mattermost.com

**Comment by justinegeffen** [comment]
@itao, I've updated the feature name but kept the content as it is still relevant imo. LMK what you think?

**Comment by itao** [comment]
Now that we have dedicated landing page and docs for this functionality and the broader DevOps Command Center vision, I think this page should actually be removed from the handbook. Also, the other pages in the Product Planning section are focused on our process and way of working rather than actual roadmap and upcoming features.

Screen Shot 2020-11-10 at 11 38 53 AM

So my suggestion would be to 🔥  this page from handbook

**Review by itao — DISMISSED** [review]
^ See my last comment, I think we should remove this page altogether from the handbook.

**Comment by justinegeffen** [comment]
Thanks, @itao. I've removed the page from the TOC. The content itself will remain in the repo (but is no longer accessible via the navigation).

**Comment by jasonblais** [comment]
@justinegeffen Why do we want to keep the content here, instead of linking to the admin docs?

**Comment by justinegeffen** [comment]
@jasonblais, that's a good point. I blanked on what we proposed so I will update this PR to:
- Have the entry removed from the TOC.
- Include a link to the admin docs in the body of the page.

**Comment by justinegeffen** [comment]
@cwarnermm, I've added you as reviewer so I can merge this, it just needs one approval. :)

**Review by cwarnermm — APPROVED** [review]

**Comment by cwarnermm** [comment]
An approve you shall have :)

**Pull request merged**
