### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by emilyhollinger**

### CODE REVIEW

**Comment by justinegeffen** [comment]
Thanks, @emilyhollinger! I've made some changes and committed them to your branch. 

One comment around the steps: Are the section names part of the Salesforce UI? If so, I'll do a second pass and revise the formatting for them. :)

**Review by emilyhollinger — COMMENTED** [review]
@justinegeffen Thanks for looking at this.  That is correct those are part of the Salesforce UI :)

**Comment by justinegeffen** [comment]
> @justinegeffen Thanks for looking at this. That is correct those are part of the Salesforce UI :)

Great. If it's ok with you, I'll revise the formatting for them and commit the changes.

**Comment by emilyhollinger** [comment]
@justinegeffen  That works for me :)

**Review by justinegeffen — APPROVED** [review]

**Pull request merged**
