### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by natalie-hub**
Two screenshots to use for "How to update BambooHR" instructions

### CODE REVIEW

**Comment by justinegeffen** [comment]
Thanks, @natalie-hub. One recommendation is to rename the screenshots so it's clear what they're related to. I'm happy to rename them if you can let me know their function. :)

**Comment by justinegeffen** [comment]
Following up on this, @natalie-hub. LMK if you need a hand with the screenshots. :)

**Comment by jasonblais** [comment]
@justinegeffen I think it's okay to go ahead with renaming :+1: 

Also, we should determine where in the "How to update BambooHR" instructions these screenshots should appear.

**Comment by natalie-hub** [comment]
I'm so sorry @justinegeffen - thank you for helping on this!

I can't find where I had added another section for BambooHR and was going to insert the screenshots there. That may be in another PR that I need to follow-up on. Sorry for the delay on responding to the PRs.

**Pull request closed without merging**
