### PR TITLE
Create PULL_REQUEST_TEMPLATE.md for handbook repo

### LINKED ISSUE #43: No reference to handbook guidelines in handbook PR template
When creating a new PR for handbook there's no reference to handbook guidelines, only generic PR description, which seems more for code PRs than doc PRs

image

### PR DESCRIPTION
**Pull request by jasonblais**
Fixes https://github.com/mattermost/mattermost-handbook/issues/43

### CODE REVIEW

**Comment by amyblais** [comment]
The text looks ok, but the preview doesn't show how it's formatted.

**Comment by jasonblais** [comment]
@amyblais it's because the text inside ```<!--``` and ```-->``` doesn't render in the preview. But the text is what people see when they open a pull request

**Review by amyblais — APPROVED** [review]
I'll approve the text, but I'm unable to confirm how it's formatted.

**Comment by jasonblais** [comment]
Thanks Amy! Merging, this is how it looks like now when you open a new pull request:

image

**Pull request merged**
