### PR TITLE
Move DevRel from Marketing to R&D>Product

### PR DESCRIPTION
**Pull request by jasonblais**
This may need a 301 redirect added to avoid broken links (@justinegeffen)

### CODE REVIEW

**Review by aspleenic — DISMISSED** [review]
Looks like a valid change

**Comment by justinegeffen** [comment]
Redirect added; will be able to test once in prod.

**Review by justinegeffen — APPROVED** [review]

**Comment by justinegeffen** [comment]
@jasonblais: FYI Redirect confirmed as working in prod.

**Comment by jasonblais** [comment]
Great, thank you!

**Pull request merged**
