### PR TITLE
Adding public speaking page

### PR DESCRIPTION
**Pull request by jespino**
#### Summary

This adds the page for clarifying what it means to do public speaking
for Mattermost staff.

This covers things like what I can apply for, what is covered by the
company in term of costs and what is the kind of themes and that we are
applying for.

### CODE REVIEW

**Review by azigler — DISMISSED** [review]
This is excellent -- thanks for preparing it! I cleaned it up for grammar and added supporting links to company expense policies, the ~DevRelOps channel, and our PgM tracking spreadsheet.

**Review by fmartingr — DISMISSED** [review]

**Comment by jespino** [comment]
@azigler I love your changes. I made a fix, and I added another Q/A to address something that your changes removed, PTAL just in case you see something wrong in my changes.

**Review by larkox — APPROVED** [review]

**Review by cwarnermm — APPROVED** [review]

**Review by jasonblais — APPROVED** [review]

**Comment by jespino** [comment]
@azigler I would love to have another approval taking into account the tiny changes made in the document after your suggestions.

**Review by azigler — APPROVED** [review]
Looks good!

**Pull request merged**
