### PR TITLE
Deprecate core committers list

### PR DESCRIPTION
**Pull request by lieut-data**
#### Summary
After some reflection on how frequently this document gets out of date, we're proposing simply removing the list altogether from the handbook.

Historically, we have tried many times to keep this document fresh, but as it's not the source of truth, it often gets forgotten. Moving forward, we expect to rely more heavily on Mattermost and GitHub groups to help with discovery issues.

### CODE REVIEW

**Review by cwarnermm — APPROVED** [review]
This decision makes a lot of sense, @lieut-data, given the maintenance challenge. Thanks!

**Comment by justinegeffen** [comment]
I'd like to recommend retaining the "how to promote someone to core committer" section. It seems relevant and we don't have that content elsewhere in the handbook that I'm aware of.

**Comment by cwarnermm** [comment]
CC @justinegeffen There may be additional places across the Handbook site where we need to update links to core committers.

**Comment by justinegeffen** [comment]
Just a note; I believe there are references to this page in other places of the Handbook. I can review and make the relevant changes once this is merged. It's a good opportunity to direct readers to the relevant team channels. @lieut-data, would you recommend directing people to a GitHub page instead?

**Review by jwilander — APPROVED** [review]

**Review by justinegeffen — APPROVED** [review]

**Pull request merged**
