### PR TITLE
Update contributing-content.md

### PR DESCRIPTION
**Pull request by aedott**
We're revising our content submission guidelines in the handbook -- please take a look and provide any feedback. Thank you!

### CODE REVIEW

**Review by lieut-data — DISMISSED** [review]
This is really readable and clear, @aedott! One question: might we consider the developer blog for any articles that don't meet the criteria for the Mattermost Blog? That is, if a developer "starts there", we follow this process to promote it up if applicable, but otherwise avoid disruption to the existing flow?

**Comment by aedott** [comment]
Thanks @lieut-data!

Moving forward we'd like to merge the developer blog with the Mattermost blog so we aren't splitting our audience between two sites. However, I haven't seen a single post on the dev blog in the year I've been here that wouldn't be a good fit for the Mattermost blog.

**Review by jasonblais — APPROVED** [review]
Thank you Ashley!

**Review by zefhemel — APPROVED** [review]
This looks really good. I like how it focuses more on encouraging (this is what we're looking for/interested in) rather than blocking/throwing up barriers ("these are the criteria, this is what you need to do to...") 👍🏻

**Review by jwilander — APPROVED** [review]

**Pull request merged**
