### PR TITLE
Updated link for Hacktoberfest2021 in resources

### LINKED ISSUE #860: Update link for Hacktoberfest 2021
The `Mattermost Hacktoberfest Tips` link in the Resources leads to the documentation of Hacktoberfest 2018. It should direct to the Tips for Hacktoberfest 2021 now.

image

### PR DESCRIPTION
**Pull request by noviicee**
#### Summary

The Mattermost Hacktoberfest Tips link in the Resources lead to the documentation of Hacktoberfest 2018. It will now direct to the Tips for Hacktoberfest 2021.

closes #860

### CODE REVIEW

**Review by jasonblais — APPROVED** [review]
Thank you!

**Comment by emilyacook** [comment]
Thanks for participating in Hacktoberfest! You can claim your sticker set here: https://get.printfection.com/hacktober21/4144583267 @noviicee

**Comment by noviicee** [comment]
> Thanks for participating in Hacktoberfest! You can claim your sticker set here: https://get.printfection.com/hacktober21/4144583267 @noviicee

Thank you 💟

**Pull request merged**
