### PR TITLE
Add developer conference policy to summary.md

### PR DESCRIPTION
**Pull request by jwilander**
#### Summary
Missed adding this in #1089.

### CODE REVIEW

**Review by cwarnermm — APPROVED** [review]
Thanks, @jwilander!

**Comment by cwarnermm** [comment]
@justinegeffen - Merged with 1 approval to confirm that the new page shows up after being added to the nav pane.

**Comment by cwarnermm** [comment]
@jwilander - Your new page is now accessible: https://handbook.mattermost.com/operations/research-and-development/engineering/how-to-go-to-conference

**Comment by jwilander** [comment]
Thanks @cwarnermm !

**Pull request merged**
