### PR TITLE
Create mattermost-communication.md

### PR DESCRIPTION
**Pull request by natalie-hub**
Create new page for Mattermost Communication best practices/guideline 

Copied more content from https://docs.mattermost.com/process/training.html#mattermost-staff-meetings

### CODE REVIEW

**Comment by natalie-hub** [comment]
Hi @jasonblais  - feel free to edit anything that feels off. With more new hires joining from different timezones, I'm hoping to update the handbook with more info on how we communicate and operate since time zone overlap may become more difficult.

**Review by natalie-hub — COMMENTED** [review]
Forgot the .md - thank you Justine!

**Review by justinegeffen — APPROVED** [review]

**Review by jasonblais — APPROVED** [review]
Thank you Natalie! We have a lot of information at https://docs.mattermost.com/process/training.html, wondering if it would be worth migrating some more of these points into the new handbook as well?

**Comment by jasonblais** [comment]
@justinegeffen Before merging, we should add to SUMMARY.md file, so that this page appears in the left-hand navigation.

**Comment by natalie-hub** [comment]
@jasonblais - definitely. I think the bulk of this info is in the handbook, but in various places. There's a few things like Channels and Avatars that I want to update, and I'd like to also add in Team meetings that are open for anyone to attend. I'll add this as a project to do a closer audit of info that hasn't been transitioned yet and may need to be updated.

**Comment by natalie-hub** [comment]
Hi @justinegeffen - should I recreate this page with the SUMMARY.md file? If yes, can you share how to do that?

**Pull request merged**
