### PR TITLE
Mattermost Consulting Agreement PDF

### PR DESCRIPTION
**Pull request by TQuock**
Mattermost Consulting Agreement PDF as of 2/28/2022

### CODE REVIEW

**Comment by it33** [comment]
Thanks @TQuock! 

Slight tweak, could we use a Word doc instead? In the past we've had vendors fill out the template for us, and it's even faster to procure. 

Legal can just run a diff against the template to see terms that have changed.

**Comment by it33** [comment]
@TQuock I'm not able to download the PDF for some reason, so if it's one of those form fill things that could work too, I just can't see the doc

**Comment by TQuock** [comment]
@it33 talked to Carrie and Justine, and apparently, it's not easy to do PDFs in GitHub. You can reject this review and I'll add a link to the PDF in google drive, but make the permissions available to anyone (internal or external).

**Comment by justinegeffen** [comment]
@TQuock, what about a Google Form instead of a PDF or Word doc? That may be a faster user experience than opening a GDrive link and downloading a form?

**Comment by TQuock** [comment]
Thanks @justinegeffen! That is definitely something to think about in the future if a use case comes up. For this particular example, not sure it makes the most sense to put this in a google form given this is a consulting agreement.

**Comment by justinegeffen** [comment]
@it33, if this change is good to go I'm happy to merge it. Thank you!

**Review by it33 — APPROVED** [review]

**Pull request merged**
