### PR TITLE
Update recruiting.md

### PR DESCRIPTION
**Pull request by justinegeffen**
Removed hyphen spacing for number range.

### CODE REVIEW

**Comment by justinegeffen** [comment]
@natalie-hub, let me know if this is good to go - they're minor cosmetic changes, no content changes.

**Comment by justinegeffen** [comment]
@natalie-hub, following up on this. :)

**Review by cwarnermm — DISMISSED** [review]
Looks great!

**Comment by justinegeffen** [comment]
Sorry, @cwarnermm, could you re-approve? I realized I'd deleted something erroneously so had to replace it.

**Review by cwarnermm — APPROVED** [review]
Looks great a second time too :)

**Pull request merged**
