### PR TITLE
Remove recommended readings link

### PR DESCRIPTION
**Pull request by javaguirre**
Recommended readings link doesn't go anywhere, I searched for an alternative in the handbook, but there is no alternative page in terms of books or readings, so I'd say let's remove it until there is something to link there. WDYT?

Thank you!

### CODE REVIEW

**Comment by justinegeffen** [comment]
Thank you for this PR! You've identified an important knowledge gap and I have created a new PR with content so we can update the link to the correct one. I'm marking this as a WIP until that PR is merged.

**Comment by javaguirre** [comment]
That solution is much better than mine, Thank you @justinegeffen ! :-)

**Comment by justinegeffen** [comment]
The solution wouldn't have come about if not for your PR, so thank YOU! :)

**Comment by TQuock** [comment]
@javaguirre thanks for catching

@justinegeffen is the linked to be replaced with the correct link. I am only seeing it be deleted.

**Comment by justinegeffen** [comment]
Thanks Tim! Just waiting for the related PR to be approved and then I'll add the new link. Apologies for the confusion.

**Comment by justinegeffen** [comment]
Updated the link.

**Review by TQuock — APPROVED** [review]

**Comment by TQuock** [comment]
approved the changes. Thanks all!

**Pull request merged**
