### PR TITLE
Update SUMMARY.md

### PR DESCRIPTION
**Pull request by TQuock**
Update ToC for Finance page to organize contents. Will look to move contents from the "How to .." section above to be Finance specific

### CODE REVIEW

**Comment by TQuock** [comment]
@justinegeffen I will be updating the branches as well to move under Finance. This will be done at a later date once I have properly organized everything

**Comment by justinegeffen** [comment]
Adding @jasonblais just for visibility into the TOC changes.

**Review by jasonblais — COMMENTED** [review]
Thanks Tim!!

Two quick notes:
1. This will cause existing links to break. @justinegeffen we may want to have a blank page for the files we're moving with a link to its new location, similar to how we do it in docs. This avoids people clicking old bookmarks and hitting a 404
2. Let's also remove the related pages from the "Company Operations" section

**Comment by TQuock** [comment]
@jasonblais Thanks for your review! 

I will also be doing some more moving around and wondering what is most preferable thing to do as I see it does take some work to move these files around. I would ideally not like to break links because we do a lot of linking and then having to comb through the 404 pages would take time. I also don't like that the ToCs don't match the root of where the files in GitHub because it takes more time to find where things are located. All that said, I want to make you and @justinegeffen lives as easy as possible.

**Comment by jasonblais** [comment]
@TQuock Yeah, both of the problems you describe unfortunately stem from GitBook. There isn't much we can do to resolve them at this point.

**Comment by TQuock** [comment]
@jasonblais thanks for the feedback. Is this something if we just redo now and spend the time to make the adjustments, update the broken link, etc. that it will fix the problem. Going forward, with any future new page or ToC, this wont be an issue going forward as these PR are being done in GitHub and not GitBook?

**Comment by justinegeffen** [comment]
@TQuock, the problem is with Gitbook itself and the way it manages links. Although we submit PRs in GitHub, they're pushed to Gitbook which manages the output so we can't work around it. The way we address is this that all the pages that were moved would need to have a note added to their original page with a link indicating the new location. 

@jasonblais, we are able to set up [redirects](https://docs.gitbook.com/integrations/github/content-configuration) in the ``gitbook.yaml`` file but I couldn't find that here. Or we could try this [plugin](https://tech.shutterstock.com/2018/11/05/gitbook-plugin-related-links)? Otherwise I am +1 on what you suggested.

**Comment by jasonblais** [comment]
+1 to what @justinegeffen said.

@justinegeffen If we can set up redirects, that would be much better. Should we create a `gitbook.yaml` file and try a redirect to see if it works?

If set up, then @TQuock wouldn't need to worry about breaking links if the page path changes -- or we need to is ensure there's a redirect in the `gitbook.yaml` file.

**Comment by justinegeffen** [comment]
@jasonblais, I'm very happy with that idea. It'll make life much easier. I'll look into it tomorrow. :)

**Comment by jasonblais** [comment]
@justinegeffen :+1:

> I'll look into it tomorrow. :)

Or Monday as tomorrow is friends and family day ;)

**Comment by justinegeffen** [comment]
I meant Monday, of course. :D

**Comment by justinegeffen** [comment]
FYI, I didn't have a chance to look at this today. I have created a Jira issue on my board: https://mattermost.atlassian.net/browse/MM-29536 in the meantime.

**Comment by justinegeffen** [comment]
I'll be looking at, and hopefully adding, the redirect script this weekend and then we can go ahead with the restructure plans.

**Review by justinegeffen — APPROVED** [review]

**Pull request closed without merging**
