### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by craigwillis-mm**
Diagram of the workflow of tickets submitted from the Self Service Portal.

### CODE REVIEW

**Comment by jasonblais** [comment]
Thanks! @craigwillis-mm where/which page do you wish to add this diagram into?

**Comment by craigwillis-mm** [comment]
> Thanks! @craigwillis-mm where/which page do you wish to add this diagram into?

I'll be adding it to the support pages, probably tomorrow morning now.

**Review by emilyhollinger — COMMENTED** [review]
https://handbook.mattermost.com/operations/business-operations/customer-support

@jasonblais @craigwillis-mm I'd recommend this go under the Ticket Workflow section.  Under the General support workflow diagram.

**Review by emilyhollinger — APPROVED** [review]

**Comment by craigwillis-mm** [comment]
As soon as this is approved I can update the Support Page with this image.

**Comment by jasonblais** [comment]
@craigwillis-mm mergd

**Pull request merged**
