### PR TITLE
Update company-agreements.md

### PR DESCRIPTION
**Pull request by TQuock**
Updated to reflect more accuracy in the process on who can send e-signs for signature

### CODE REVIEW

**Review by TQuock — COMMENTED** [review]
I am approved to merge these changes to the original PR branch

**Review by justinegeffen — DISMISSED** [review]
Looks good to me, thanks Tim!

**Comment by it33** [comment]
Thanks @TQuock, really excellent work, 

Per our call, I think 

i) we need some adjustments in the authorization matrix working with @jamiehurewitz and flow that through the handbook update,

ii) Also, in reviewing the latest, wondering if we break this PR out into some iterations (i.e. separate PRs), and start with an overview/context. I have a draft of some of the context we discussed on the phone below. 

After we get feedback from you and JLH on the below, we can break out the PRs. It's probably easier to review things by iteration/section rather than all at once in my mind, 

1. **Context** - For teams outside of G&A/legal, we might set out our intention at the top of the page, e.g.: 

The purpose of our company agreement process is to make legal agreement decisions correctly, effectively and efficiently on behalf of the company. Our intended outcomes are to: 

a) balance the speed, transparency and efficiency in running our business with the appropriate amount of review and collaboration when it comes to making bespoke agreements on behalf of the company, 

b) make high impact agreement decisions quickly and effectively through explicit categorization and processes, 

c) make consistent decisions based on an understanding of our past decisions by developing and maintain an effective record of our legal agreements and precedents, 

d) continually improve, 

e) make our agreement process easy to understand for our company, as well as our customers, vendors, partners, and community

For e) this is updating our page. We can have links to confidential docs where we lay out the policies for different contract terms, e.g. for Enterprise SKU deals over $XXXK, who can make which concessions on non-conforming agreements. 

2. **Contract Management Process & Categorization** - So a summary of the methods by which we'll operate, e.g.: 

Summarize our processes (most of which is detailed in TQ's PR, and this would be a summary): 
- Contract development // link to templates 
- Legal review (if not unmodified standard contract) // with link to our contract management system 
- e-sign setup and routing // link to instructions/onboarding 
- Approval, signing, storage with links/anchor refs to our processes. 

Also, maybe introduce the idea of "categories", which are implicit right now, and we can make them explicit for non-G&A to more quickly understand--E.g. 

- Unmodified - Using Mattermost templates with unmodified terms, e.g. standard sales orders forms, renewal forms, vendor consulting agreements, sponsored open source project, etc.

- Conforming - Agreements with terms outside of Mattermost templates, but still conforming to an explicit set of conforming criteria (e.g. jurisdiction venue not in California, but in UK, or customer payment terms at 45 days instead of 30 days, etc.). Conforming agreements are essentially an "allow-list" of contract terms to speed review and approvals // requires both legal review (since it's not unmodified) and at least one Director-level initialler on the e-sign agreement, and potentially requires other approvers (e.g. security if the agreement is with a vendor where Mattermost has a security dependency), but doesn't require CEO typically. 

- Non-Conforming - Agreements that are neither standard nor conforming. Requires legal, VP Finance, CEO review. This category requires the most review and takes the longest, and should be reserved for high impact agreements and decisions. Non-conforming contracts should be hard decisions. If they are easy-decisions, then given intended outcome d) ("continually improve") we should be updating our process to make the contract type conforming, and being explicit about where the delegation is made. 

3. **Roles** - Overview of roles

In TQ's PR we have explicit mapping of people and roles, this would be a summary of the role types and expectations. E.g. 

- Contract setup // link to TQ's matrix
- Required approval // link to TQ's matrix  
- Initiallers // link to TQ's matrix

We also might include what training and tooling is required for each (the story in my head, which could be totally wrong, is there are some people sending e-signs right now that haven't reviewed the handbook page). 

For signers, I would leave that out of documentation, we aren't at the point yet where it's anyone outside of CEO, VP F and Legal.

**Comment by TQuock** [comment]
@it33 this is still an outstanding PR. Did Jamie and you get around to making the adjustments you discussed above?

**Comment by justinegeffen** [comment]
@TQuock, just following up on this. :)

**Comment by it33** [comment]
@justinegeffen we have a new VP Legal and she's working on some docs around risk management, that we would review with @TQuock. Maybe leave this one with me? 

It'll probably be a G Doc to start, and we'll work it into the handbook a little later

**Comment by justinegeffen** [comment]
Perfect, thanks @it33! I've marked it as WIP.

**Comment by cwarnermm** [comment]
Closing this legacy PR.

**Pull request closed without merging**
