### PR TITLE
Thin Open Core link update

### PR DESCRIPTION
**Pull request by javaguirre**
Hi!

The Thin Open Core link gives a 404 (https://medium.com/open-consensus/2-open-core-definition-examples-tradeoffs-e4d0c044da7c). Since I couldn't find a good replacement for the `Thin Core Model`, maybe we could update it with the `Open Core model` article in Wikipedia at least to have some context of the term?

Thank you!

### CODE REVIEW

**Comment by justinegeffen** [comment]
Great suggestion, thank you for this! Really appreciate your contribution. :) Please let me know when you've had a chance to sign the CLA so we can move ahead with merging this. :)

**Review by jasonblais — COMMENTED** [review]
Thanks Javier :+1:

**Review by jasonblais — APPROVED** [review]

**Comment by javaguirre** [comment]
The CLA passed! 👏 

Thank you @jasonblais !

**Review by jasonblais — APPROVED** [review]

**Comment by jasonblais** [comment]
Thank you @javaguirre :tada:

**Pull request merged**
