### PR TITLE
Add cloud cost reporting links and sheets

### PR DESCRIPTION
**Pull request by angeloskyratzakos**
#### Summary
Update Cloud cost reporting page with useful links on how Cloud Cost Optimization Reports are being generated.

#### Ticket
https://mattermost.atlassian.net/browse/CLD-6796

### CODE REVIEW

**Review by stylianosrigas — DISMISSED** [review]

**Review by andrleite — DISMISSED** [review]

**Review by andrleite — APPROVED** [review]

**Comment by cwarnermm** [comment]
@spirosoik - Friendly ping on this open Handbook PR.

**Review by stafot — APPROVED** [review]
LGTM

**Review by spirosoik — APPROVED** [review]

**Comment by angeloskyratzakos** [comment]
@cwarnermm - Could you please take a look and merge it when you have some time? Thank you!

**Review by cwarnermm — APPROVED** [review]
Thanks, @angeloskyratzakos!

**Pull request merged**
