### PR TITLE
Update how-to-procure-a-vendor-contract.md

### PR DESCRIPTION
**Pull request by wiersgallak**
Fixed broken link

### CODE REVIEW

**Review by TQuock — APPROVED** [review]
thanks for catching this @wiersgallak. didn't realize this link was broken.

@justinegeffen - are there are other redirct links that we should explore?

**Comment by justinegeffen** [comment]
Thanks, @wiersgallak! @TQuock, this has been added to the redirect file but I suspect it's not set up correctly. I've added links and their redirects as we've been moving things around and checking on Google Analytics to pick up outliers but this must have slipped through the cracks. I'll review the redirect file.

**Comment by justinegeffen** [comment]
Looking at this PR again, @wiersgallak, could you link me to the page where you encountered this erroneous link? Thank you!

**Comment by wiersgallak** [comment]
@justinegeffen I don't have it saved anymore.  It was giving me an error "This page does not exist" so I just found it in the navigation, which is what prompted me to create the PR.

**Comment by justinegeffen** [comment]
Gotcha! Reason I ask is because I can't find it in the LHS navigation on the live site and wanted to check whether the redirect I'd set up was broken. I think the page has been moved around and possibly renamed on the live site - either way, thanks for the PR! Gitbook doesn't handle pages being moved and the redirect process is a WIP and there are sometimes errors like this one. :)

**Pull request merged**
