### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by justinegeffen**
Edited the leadership principles, minor formatting changes, general content check.

### CODE REVIEW

**Comment by justinegeffen** [comment]
@amynicol1985, this PR is the same as the one you opened but I adjusted some of the values based on the slide. If you're happy with it, can we merge this one and close yours?

**Comment by justinegeffen** [comment]
This is yours, for reference: https://github.com/mattermost/mattermost-handbook/pull/668

**Comment by justinegeffen** [comment]
@jasonblais, there are a few open PRs for this change. If you don't mind approving this one then I can close the others. :) Thank you!

**Review by jasonblais — APPROVED** [review]
As a note, some of the other PRs change additional files where the leadership principles are referenced, so they may still be valid

**Comment by justinegeffen** [comment]
Good point, thanks Jason. I'll re-review them. :)

**Pull request merged**
