### PR TITLE
address some typos in handbook

### PR DESCRIPTION
**Pull request by seanohue**
#### Summary

I'm reading through the handbook in hopes of contributing during Hacktoberfest, and this PR contains any small typo fixes I've noticed.

- "Boarder" should be "broader" based on the context present
- Consider using "decision-making" consistently rather than "decision making" in some places and "decision making" in others.

### CODE REVIEW

**Review by justinegeffen — COMMENTED** [review]
Thanks a lot for this really helpful PR! I agree with your suggestion to hyphenate "decision-making". I'll add that to our general terminology guideline and we'll work through the handbook to make it consistent. :)

**Comment by justinegeffen** [comment]
In terms of hacktoberfest contributions, I haven't yet tagged any of our issues as such - if you're open to assisting with making "decision-making" consistent I can create an issue for that and would welcome the help. :)

**Comment by seanohue** [comment]
> if you're open to assisting with making "decision-making" consistent I can create an issue for that and would welcome the help.

@justinegeffen I can definitely do that, feel free to tag or assign me on the issue. Thanks!

**Review by justinegeffen — APPROVED** [review]

**Comment by justinegeffen** [comment]
@seanohue, I've created this issue https://github.com/mattermost/mattermost-handbook/issues/1096 but can't assign you for some reason. :)

**Pull request merged**
