### PR TITLE
Create QA handbook pages and add initial info

### PR DESCRIPTION
**Pull request by lindalumitchell**
- Create folder /research-and-development/quality, plus /README.md
- Create subfolder /research-and-development/quality/qa-workflow, plus /README.md
- Create page /research-and-development/quality/testing-tips-and-tools.md
- Update TOC at /SUMMARY.md to add Quality Assurance section

### CODE REVIEW

**Review by lindy65 — DISMISSED** [review]
Thanks @lindalumitchell, looks good to me 👍

**Review by justinegeffen — APPROVED** [review]

**Comment by justinegeffen** [comment]
Thanks, @lindalumitchell! I made some formatting changes and committed them. One question around the READMEs. Are those going to be populated with content or are they stand-alone headers?

**Comment by lindalumitchell** [comment]
> Thanks, @lindalumitchell! I made some formatting changes and committed them. One question around the READMEs. Are those going to be populated with content or are they stand-alone headers?

Thanks @justinegeffen! I had intended them to be stand-alone headers, as it appeared that's the way Product structured theirs, and I wanted to be consistent. But I'm totally open to reorganizing that aspect.

**Comment by lindalumitchell** [comment]
@lindy65 it looks like after Justine fixed up some formatting it wanted you to review it again, so I officially re-requested your review. :)  Thanks for the help!

**Review by lindy65 — APPROVED** [review]
Cool, thanks @lindalumitchell 👍

**Comment by justinegeffen** [comment]
Thanks, @lindalumitchell - it all looks good to me, just wanted to confirm the structure. I'm 5/5 on replicating the structure of other sections - consistency is awesome. :)

**Comment by lindalumitchell** [comment]
Yay, thanks @justinegeffen! I don't have permission to merge in this repo; do you usually merge handbook PRs? (Or I guess I could just ask: could you help merge this for me please? :) )

**Pull request merged**
