### PR TITLE
Create software-systems.md

### PR DESCRIPTION
**Pull request by danielsischy**

### CODE REVIEW

**Review by justinegeffen — DISMISSED** [review]

**Comment by jasonblais** [comment]
Thanks @danielsischy ,where would you like it to appear in the table of contents? https://handbook.mattermost.com/

**Review by TQuock — DISMISSED** [review]

**Comment by danielsischy** [comment]
@jasonblais It would live under Workplace > IT https://handbook.mattermost.com/operations/workplace/it

**Comment by jasonblais** [comment]
Thanks! @justinegeffen would you be open to help add it to the TOC?

**Comment by justinegeffen** [comment]
> Thanks! @justinegeffen would you be open to help add it to the TOC?

On it. :)

**Review by justinegeffen — APPROVED** [review]

**Comment by jasonblais** [comment]
Thank you!

**Pull request merged**
