### PR TITLE
[GH-1105] - WIP - Documentation style guide revision

### PR DESCRIPTION
**Pull request by ghost**
#### Summary

This PR is for revisions to the Documentation style guide in the technical writing section of the handbook. It is a WIP, any feedback is welcome. So far this PR:

- Moves RST and MD content to new pages
- Re-orders the style guide sections
- Removed a few passages that seemed unnecessary

This is related to https://github.com/mattermost/mattermost-handbook/issues/1105.

### CODE REVIEW

**Comment by justinegeffen** [comment]
This is awesome, Matthew! The handbook doesn't have a preview build so we just merge and iterate as needed. This looks great to me - let me know if you want to merge to see the changes or if you work locally and are using local builds to track.

**Comment by ghost** [comment]
Thank you @justinegeffen. I am still working on this, so please wait to merge.

**Review by cwarnermm — DISMISSED** [review]
Thank you, @matthew-src!

**Comment by ghost** [comment]
Hi @justinegeffen and @cwarnermm, I made a few more edits to the guide, and added the new pages for RST and MD to the SUMMARY.md page. I hope this means that they will appear in the navigation bar of the Gitbook. Feel free to merge this now to see the changes.

**Review by justinegeffen — APPROVED** [review]

**Comment by justinegeffen** [comment]
@matthew-src, I'm so sorry - I merged this before reviewing it thoroughly and noticed some changes that I wanted to query so I've reverted the changes which means they need to be redone. I'm going to redo them on my side as I messed up. I did have some questions about the content that was removed but will raise them in the new PR.

Sorry about this; I know this wasn't a quick one to put together.

**Comment by ghost** [comment]
No problem!

**Comment by justinegeffen** [comment]
In terms of an ETA, I'll aim to get this redone by Friday. Thanks for understanding! :)

**Pull request merged**
