### PR TITLE
Create cloud-data-export-process.md

### PR DESCRIPTION
**Pull request by jasonblais**

### CODE REVIEW

**Review by stafot — APPROVED** [review]
Looks good to me!

**Comment by jasonblais** [comment]
@svelle Would you be open to help with a review? We are preparing for more Cloud users with Oct 13 launch, and anticipate more people migrating from Cloud to Self-Hosted. Just want to ensure eng + support have a clear process to follow.

If any questions or concerns, let me know.

cc @DSchalla in case you wanted to review from security perspective

**Comment by svelle** [comment]
Thank you @jasonblais this is super helpful.

Okay from my side to merge.

**Review by svelle — APPROVED** [review]

**Review by justinegeffen — APPROVED** [review]

**Comment by jasonblais** [comment]
Thanks all!

**Pull request merged**
