### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by justinegeffen**
Rectified incorrect placement of laptop paragraph.

### CODE REVIEW

**Review by ialorro — APPROVED** [review]
Approve the change - thank you!

**Review by amyblais — APPROVED** [review]

**Review by TQuock — APPROVED** [review]
changes look good to me

**Comment by ialorro** [comment]
Hi @justinegeffen @amyblais can we please publish this change in the handbook? I have to make another update in this section and I would like to make sure that this change come through before I submit the new pull request. Thank you in advance! cc @TQuock

**Comment by justinegeffen** [comment]
Thanks, @ialorro, it's merged. :)

**Comment by ialorro** [comment]
@justinegeffen thank you!

**Pull request merged**
